"""Initial migration

Revision ID: a6def3c4127b
Revises: 81efa325d3ab
Create Date: 2025-08-20 00:00:28.282730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6def3c4127b'
down_revision = '81efa325d3ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###